name: Run tests

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

jobs:
  test:
    strategy:
      matrix:
        version: [ 2.7,2.6,2.5 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      env:
        RUBY_VER: ${{ matrix.version }}
      run: make test
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: prepare artifact
      run: cp docker.mk Makefile && tar -czf docker4ruby.tar.gz docker-compose.yml mutagen Makefile .env traefik.yml
    - uses: xresloader/upload-to-github-release@v1
      id: upload_artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: docker4ruby.tar.gz
        overwrite: true
        tags: true
        draft: false
        tag_name: ${GITHUB_REF##*/}