name: Run tests

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

jobs:
  test:
    strategy:
      matrix:
        version: [ 2.7,2.6,2.5 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      env:
        RUBY_VER: ${{ matrix.version }}
      run: make test
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: prepare artifact
      run: cp docker.mk Makefile && tar -czf docker4ruby.tar.gz docker-compose.yml mutagen Makefile .env traefik.yml
    - uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/:repository/releases/latest
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: get upload url
      id: get_upload_url
      uses: pdamianik/release-tag-to-upload-url-action@v1.0.1
      with:
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{steps.get_upload_url.uploadUrl}}
        asset_path: ./docker4ruby.tar.gz
        asset_name: docker4ruby.tar.gz
        asset_content_type: application/tar+gzip
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      test
